version: 2
jobs:
  build_deploy:
    docker:
      - image: node:12
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e0:44:26:96:02:80:9d:84:ac:ed:b7:16:49:47:08:79"
      - restore_cache:
          keys:
            - npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - npm-packages-{{ .Branch }}
            - npm-packages-master
            - npm-packages-
      - run:
          name: Install Node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_moduels
          key: npm-packages-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Deploy
          command: |
            git config --global user.name "Circle CI"
            git config --global user.email "<>"
            npm run deploy:github
      - run:
          name: Publish package
          command: |
            echo "//registry.npmjs.org/:_authToken=${npmToken}" > ~/.npmrc
            npm whoami
            npm run build
            npm publish
workflows:
  version: 2
  deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: 
                - master